include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - sort_child_properties_last
    - require_trailing_commas
    - unnecessary_string_escapes
