import 'dart:ui' show lerpDouble;
import 'package:flutter/material.dart';

enum MouthShape { flat, smile, openSmile, frown, open, oShape, smirk, sad }

class MascotEmotionConfig {
  final double eyeOpenLeft;
  final double eyeOpenRight;
  final double irisScale;
  final double pupilScale;
  final Offset gaze;
  final MouthShape mouth;
  final double mouthWidth;
  final double mouthCurve;
  final double blushOpacity;
  final double glowOpacity;
  final double headTilt;
  final double bounce;

  const MascotEmotionConfig({
    this.eyeOpenLeft = 1.0,
    this.eyeOpenRight = 1.0,
    this.irisScale = 0.55,
    this.pupilScale = 0.55,
    this.gaze = Offset.zero,
    this.mouth = MouthShape.flat,
    this.mouthWidth = 0.4,
    this.mouthCurve = 0.0,
    this.blushOpacity = 0.0,
    this.glowOpacity = 0.0,
    this.headTilt = 0.0,
    this.bounce = 0.0,
  });

  MascotEmotionConfig lerp(MascotEmotionConfig to, double t) {
    if (t <= 0) return this;
    if (t >= 1) return to;
    return MascotEmotionConfig(
      eyeOpenLeft: lerpDouble(eyeOpenLeft, to.eyeOpenLeft, t)!,
      eyeOpenRight: lerpDouble(eyeOpenRight, to.eyeOpenRight, t)!,
      irisScale: lerpDouble(irisScale, to.irisScale, t)!,
      pupilScale: lerpDouble(pupilScale, to.pupilScale, t)!,
      gaze: Offset(
        lerpDouble(gaze.dx, to.gaze.dx, t)!,
        lerpDouble(gaze.dy, to.gaze.dy, t)!,
      ),
      mouth: t < 0.5 ? mouth : to.mouth,
      mouthWidth: lerpDouble(mouthWidth, to.mouthWidth, t)!,
      mouthCurve: lerpDouble(mouthCurve, to.mouthCurve, t)!,
      blushOpacity: lerpDouble(blushOpacity, to.blushOpacity, t)!,
      glowOpacity: lerpDouble(glowOpacity, to.glowOpacity, t)!,
      headTilt: lerpDouble(headTilt, to.headTilt, t)!,
      bounce: lerpDouble(bounce, to.bounce, t)!,
    );
  }
}

final Map<String, MascotEmotionConfig> emotionConfigs = {
  'neutral': const MascotEmotionConfig(
    mouthWidth: 0.35,
  ),
  'calm': const MascotEmotionConfig(
    eyeOpenLeft: 0.85,
    eyeOpenRight: 0.85,
    mouth: MouthShape.smile,
    mouthCurve: 0.04,
    mouthWidth: 0.3,
  ),
  'curious': const MascotEmotionConfig(
    irisScale: 0.6,
    pupilScale: 0.6,
    mouth: MouthShape.oShape,
    mouthWidth: 0.2,
    headTilt: 0.03,
    glowOpacity: 0.1,
  ),
  'thinking': const MascotEmotionConfig(
    eyeOpenLeft: 0.7,
    eyeOpenRight: 0.7,
    irisScale: 0.5,
    pupilScale: 0.45,
    gaze: Offset(0.0, -0.3),
    mouth: MouthShape.oShape,
    mouthWidth: 0.15,
    headTilt: 0.05,
  ),
  'reading': const MascotEmotionConfig(
    eyeOpenLeft: 0.8,
    eyeOpenRight: 0.8,
    irisScale: 0.5,
    pupilScale: 0.45,
    gaze: Offset(0.0, 0.3),
    mouthWidth: 0.25,
    headTilt: -0.02,
  ),
  'serious': const MascotEmotionConfig(
    eyeOpenLeft: 0.6,
    eyeOpenRight: 0.6,
    irisScale: 0.45,
    pupilScale: 0.5,
    mouthWidth: 0.45,
    mouthCurve: -0.01,
  ),
  'happy': const MascotEmotionConfig(
    eyeOpenLeft: 0.7,
    eyeOpenRight: 0.7,
    irisScale: 0.5,
    mouth: MouthShape.smile,
    mouthCurve: 0.12,
    mouthWidth: 0.5,
    blushOpacity: 0.4,
  ),
  'excited': const MascotEmotionConfig(
    irisScale: 0.6,
    pupilScale: 0.6,
    mouth: MouthShape.openSmile,
    mouthCurve: 0.15,
    mouthWidth: 0.55,
    blushOpacity: 0.5,
    glowOpacity: 0.25,
    bounce: 0.03,
  ),
  'confused': const MascotEmotionConfig(
    eyeOpenRight: 0.6,
    pupilScale: 0.5,
    mouth: MouthShape.smirk,
    mouthWidth: 0.3,
    mouthCurve: 0.02,
    headTilt: -0.04,
  ),
  'worried': const MascotEmotionConfig(
    irisScale: 0.6,
    pupilScale: 0.5,
    gaze: Offset(0.0, -0.1),
    mouth: MouthShape.frown,
    mouthWidth: 0.3,
    mouthCurve: -0.06,
    headTilt: 0.02,
  ),
  'sad': const MascotEmotionConfig(
    eyeOpenLeft: 0.55,
    eyeOpenRight: 0.55,
    irisScale: 0.5,
    pupilScale: 0.4,
    gaze: Offset(0.0, 0.15),
    mouth: MouthShape.sad,
    mouthWidth: 0.3,
    mouthCurve: -0.08,
    blushOpacity: 0.2,
    headTilt: -0.02,
  ),
  'embarrassed': const MascotEmotionConfig(
    pupilScale: 0.5,
    gaze: Offset(0.0, -0.2),
    mouth: MouthShape.smile,
    mouthWidth: 0.25,
    mouthCurve: 0.03,
    blushOpacity: 0.8,
    headTilt: -0.05,
  ),
  'annoyed': const MascotEmotionConfig(
    eyeOpenLeft: 0.5,
    eyeOpenRight: 0.5,
    irisScale: 0.45,
    pupilScale: 0.5,
    gaze: Offset(-0.1, 0.0),
    mouth: MouthShape.frown,
    mouthCurve: -0.04,
    headTilt: -0.03,
  ),
  'surprised': const MascotEmotionConfig(
    irisScale: 0.65,
    pupilScale: 0.4,
    mouth: MouthShape.open,
    glowOpacity: 0.15,
  ),
  'winking': const MascotEmotionConfig(
    eyeOpenRight: 0.0,
    mouth: MouthShape.smirk,
    mouthWidth: 0.35,
    mouthCurve: 0.08,
  ),
  'proud': const MascotEmotionConfig(
    eyeOpenLeft: 0.75,
    eyeOpenRight: 0.75,
    pupilScale: 0.6,
    mouth: MouthShape.smile,
    mouthCurve: 0.1,
    mouthWidth: 0.45,
    blushOpacity: 0.3,
    glowOpacity: 0.1,
    headTilt: -0.02,
  ),
  'celebrating': const MascotEmotionConfig(
    eyeOpenLeft: 0.85,
    eyeOpenRight: 0.85,
    irisScale: 0.6,
    pupilScale: 0.6,
    mouth: MouthShape.openSmile,
    mouthCurve: 0.18,
    mouthWidth: 0.55,
    blushOpacity: 0.6,
    glowOpacity: 0.35,
    bounce: 0.05,
  ),
  'concentrated': const MascotEmotionConfig(
    eyeOpenLeft: 0.65,
    eyeOpenRight: 0.65,
    irisScale: 0.5,
    pupilScale: 0.5,
    mouthWidth: 0.3,
    mouthCurve: -0.02,
    headTilt: 0.01,
  ),
  'crying': const MascotEmotionConfig(
    eyeOpenLeft: 0.4,
    eyeOpenRight: 0.4,
    irisScale: 0.5,
    pupilScale: 0.4,
    gaze: Offset(0.0, 0.2),
    mouth: MouthShape.sad,
    mouthWidth: 0.35,
    mouthCurve: -0.12,
    blushOpacity: 0.3,
    headTilt: 0.03,
  ),
  'sleepy': const MascotEmotionConfig(
    eyeOpenLeft: 0.2,
    eyeOpenRight: 0.2,
    irisScale: 0.4,
    pupilScale: 0.3,
    gaze: Offset(0.0, 0.4),
    mouth: MouthShape.oShape,
    mouthWidth: 0.15,
    headTilt: -0.06,
    bounce: -0.02,
  ),
  'excitedWave': const MascotEmotionConfig(
    irisScale: 0.6,
    pupilScale: 0.6,
    mouth: MouthShape.openSmile,
    mouthCurve: 0.2,
    mouthWidth: 0.55,
    blushOpacity: 0.5,
    glowOpacity: 0.3,
    bounce: 0.06,
  ),
  'happyWings': const MascotEmotionConfig(
    eyeOpenLeft: 0.65,
    eyeOpenRight: 0.65,
    pupilScale: 0.6,
    mouth: MouthShape.openSmile,
    mouthCurve: 0.18,
    mouthWidth: 0.55,
    blushOpacity: 0.5,
    glowOpacity: 0.2,
    bounce: 0.04,
  ),
  'surprisedWings': const MascotEmotionConfig(
    irisScale: 0.65,
    pupilScale: 0.35,
    mouth: MouthShape.open,
    mouthWidth: 0.45,
    glowOpacity: 0.2,
  ),
  'pointRight': const MascotEmotionConfig(
    eyeOpenLeft: 0.85,
    gaze: Offset(0.6, 0.0),
    mouth: MouthShape.smile,
    mouthCurve: 0.06,
    mouthWidth: 0.35,
    headTilt: -0.04,
  ),
  'pointLeft': const MascotEmotionConfig(
    eyeOpenRight: 0.85,
    gaze: Offset(-0.6, 0.0),
    mouth: MouthShape.smile,
    mouthCurve: 0.06,
    mouthWidth: 0.35,
    headTilt: 0.04,
  ),
  'laughing': const MascotEmotionConfig(
    eyeOpenLeft: 0.5,
    eyeOpenRight: 0.5,
    irisScale: 0.5,
    pupilScale: 0.5,
    mouth: MouthShape.openSmile,
    mouthCurve: 0.22,
    mouthWidth: 0.6,
    blushOpacity: 0.6,
    bounce: 0.06,
  ),
  'shocked': const MascotEmotionConfig(
    irisScale: 0.7,
    pupilScale: 0.3,
    mouth: MouthShape.open,
    mouthWidth: 0.5,
    glowOpacity: 0.2,
  ),
  'whistling': const MascotEmotionConfig(
    eyeOpenLeft: 0.6,
    eyeOpenRight: 0.6,
    irisScale: 0.5,
    pupilScale: 0.45,
    mouth: MouthShape.oShape,
    mouthWidth: 0.1,
    headTilt: 0.03,
  ),
  'wink': const MascotEmotionConfig(
    eyeOpenRight: 0.0,
    mouth: MouthShape.smirk,
    mouthWidth: 0.35,
    mouthCurve: 0.08,
  ),
  'sadSoft': const MascotEmotionConfig(
    eyeOpenLeft: 0.65,
    eyeOpenRight: 0.65,
    irisScale: 0.5,
    pupilScale: 0.4,
    gaze: Offset(0.0, 0.1),
    mouth: MouthShape.sad,
    mouthWidth: 0.3,
    mouthCurve: -0.06,
    blushOpacity: 0.15,
    headTilt: -0.02,
  ),
};
